### ISSUE TITLE
It seems like the browser window calculations does not include the size of the textual header

### ISSUE THREAD

**Issue by totto** [Cantara/visuale#593]
..meaning some services may get painted outside the visible space of the dashboard

**Comment by cicioflaviu** [comment]
Tested locally and the size of the textual header is included in the dashboard size calculation.
I managed to reproduce the issue only by removing the size of the header from the calculation code.

However, there are some behaviors that might have an impact on the size calculation:
- the size of the textual header is initially 0 for less than 1 second until the header is rendered;
- the height of the dashboard container is not manually set when the width of the window is less than 990px (mobile device);

This being said, I am wondering if there's any corner case that I've missed.
